### ISSUE TITLE
[Fix] 실기기 테스트 시 상세보기 녹음 재생 볼륨이 낮은 오류 발생

### ISSUE THREAD

**Issue by Suyeon9911** [TeamRecorDream/RecorDream-iOS#118]
### 🚨 오류 및 버그 사항

상세보기에서 녹음 재생할 때 시뮬레이터에서는 크게 잘들리는데, 실기기에서는 소리가 매우 작게 들립니다.

### ✅ 체크 리스트

- [ ] 녹음 재생 볼륨 버그 해결하기

**Comment by L-j-h-c** [comment]
@Suyeon9911 코드에서 볼륨을 한번 100으로 높여보실래요? 그럼 좀 커지는 것 같더라구요!
